project:
  type: website
  output-dir: docs


execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Schedule
      - href: 00_setup.qmd
        text: Setup
      - href: Introduction.qmd
        text: Introduction
      - text: "Day 1"
        menu:
          - text: "Exploratory Data Analysis (EDA) - Regression"
            href: 100_regression/step1.qmd
          - text: "Get started with tidymodels and workflows"
            href: 100_regression/step2.qmd
      - text: "Day 2"
        menu:
          - text: "EDA - Classification"
            href: 200_classification/step1.qmd
          - text: "Tuning hyperparameters and compare multiple model workflows"
            href: 200_classification/step2.qmd
      - href: Tidymodels_tips_tricks.qmd
        text: Tips&Tricks

  repo-url: https://github.com/Sydney-Informatics-Hub/
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-footer:
    center: "Copyright 2023, Sydney Informatics Hub"

about:
  template: solana

format:
  html:
    toc: true
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc-depth: 2
    code-link: true
    code-fold: false
    code-overflow: wrap
    code-summary: "Show the code"


