project:
  type: website
  output-dir: docs


execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Schedule
      - href: 00_setup.qmd
        text: Setup
      - href: Introduction.qmd
        text: Introduction
      - text: "Session 1"
        menu:
          - text: "Predict the house sale price in Iowa - EDA"
            href: 100_dataset1/step1.qmd
          - text: "Get started with tidymodels"
            href: 100_dataset1/step2.qmd
      - text: "Session 2"
        menu:
          - text: "Predict what makes a developer more likely to work remotely - EDA"
            href: 200_dataset2/step1.qmd
          - text: "Preprocess with a recipe"
            href: 200_dataset2/step2.qmd
      - text: "Session3 "
        menu:
          - text: "Predict which wine features are the best quality wine indicators - EDA"
            href: 300_dataset3/step1.qmd
          - text: "Create a modeling workflow"
            href: 300_dataset3/step2.qmd
      - text: "Session 4"
        menu:
          - text: "Predict whether a cancer is malignant or benign from biopsy details - EDA"
            href: 400_dataset4/step1.qmd
          - text: "Work with model hyperparameters"
            href: 400_dataset4/step2.qmd

  repo-url: https://github.com/Sydney-Informatics-Hub/
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-footer:
    center: "Copyright 2023, Sydney Informatics Hub"

about:
  template: solana

format:
  html:
    toc: true
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc-depth: 2
    code-link: true
    code-fold: false
    code-overflow: wrap
    code-summary: "Show the code"


