project:
  type: website
  output-dir: docs


execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Sydney Informatics Hub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Schedule
      - href: docs/00_setup.html
        text: Setup
      - href: docs/Introduction.html
        text: Introduction
      - text: "Day 1"
        menu:
          - text: "Exploratory Data Analysis (EDA) - Regression"
            href: docs/100_regression/step1.html
          - text: "Get started with tidymodels and workflows"
            href: docs/100_regression/step2.html
      - text: "Day 2"
        menu:
          - text: "EDA - Classification"
            href: docs/200_classification/step1.html
          - text: "Tuning hyperparameters and compare multiple model workflows"
            href: docs/200_classification/step2.html
      - href: docs/Tidymodels_tips&tricks.html
        text: Tips&Tricks

  repo-url: https://github.com/Sydney-Informatics-Hub/
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-footer:
    center: "Copyright 2023, Sydney Informatics Hub"

about:
  template: solana

format:
  html:
    toc: true
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc-depth: 2
    code-link: true
    code-fold: false
    code-overflow: wrap
    code-summary: "Show the code"


