# Predict whether a cancer is malignant or benign from biopsy details

:::{.callout-tip}
## Exercise:

This dataset, called the Breast Cancer Wisconsin (Diagnostic) Data Set, includes features computed from digitized images of biopsies. If you want to predict whether a cancer is malignant or benign from biopsies details, which model can you build?
:::

Load the libraries:
```{r}
library(RCurl)
```

Load the data:
```{r}
#load the data into a tibble using the RCurl package
UCI_data_URL <- getURL('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data') 

#create a list with the appropriate column names 
names <- c('id_number', 'diagnosis', 'radius_mean', 
         'texture_mean', 'perimeter_mean', 'area_mean', 
         'smoothness_mean', 'compactness_mean', 
         'concavity_mean','concave_points_mean', 
         'symmetry_mean', 'fractal_dimension_mean',
         'radius_se', 'texture_se', 'perimeter_se', 
         'area_se', 'smoothness_se', 'compactness_se', 
         'concavity_se', 'concave_points_se', 
         'symmetry_se', 'fractal_dimension_se', 
         'radius_worst', 'texture_worst', 
         'perimeter_worst', 'area_worst', 
         'smoothness_worst', 'compactness_worst', 
         'concavity_worst', 'concave_points_worst', 
         'symmetry_worst', 'fractal_dimension_worst') 

#load the column names into a data frame and set the column names
breast_cancer <- read.table(textConnection(UCI_data_URL), sep = ',', col.names = names) 

#discard id_number column
breast_cancer$id_number <- NULL 
```
